/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a token pair.
         *
         *     **The failure message is identical for an unknown email and a wrong
         *     password, and the password is verified either way.** Two reasons, and the
         *     second is the one people forget: a distinct "no such user" reply turns the
         *     login form into an account-enumeration oracle, and an early return on a
         *     missing user makes the response measurably faster, which leaks the same fact
         *     through timing.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Mint a new access token from a refresh token.
         *
         *     The role is re-read from the store rather than copied from the token. A
         *     supervisor demoted to officer must lose supervisor access at the next
         *     refresh, and a claim signed a fortnight ago cannot know that.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/listing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Listing
         * @description The third input channel: an e-commerce listing, no image.
         *
         *     This route is short *because* the wall holds. It parses text into a
         *     `DeclarationSet` and hands it to the same engine a photograph reaches, so
         *     every presence, format, unit-symbol and misleading-declaration rule runs
         *     unchanged, and every geometric rule returns `NO_DATA` rather than `FAIL`.
         *
         *     Section 3 predicted the cost of getting this wrong: with OCR wired into the
         *     rules "that third channel becomes a rewrite instead of an afternoon's work".
         */
        post: operations["scan_listing_api_v1_scans_listing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Replay an offline outbox. Idempotent, in the strict sense.
         *
         *     Section 5: *"Every scan gets a client-generated UUIDv7, which is
         *     time-ordered so it doubles as a sort key. Sync is idempotent, so replaying
         *     the outbox never duplicates a record."*
         *
         *     An officer's phone regains signal halfway through an upload and retries the
         *     whole batch. Every scan it already delivered comes back `created=False`, and
         *     — this is the part that matters — **no second chain entry is appended**. A
         *     duplicated chain entry would break the sequence for a client whose only
         *     mistake was losing signal.
         *
         *     Scans arrive in whatever order the outbox held them; `chain_seq` is assigned
         *     here, server-side, because "offline clients cannot possibly agree on
         *     ordering among themselves".
         */
        post: operations["sync_api_v1_scans_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Photo
         * @description The first input channel: one photograph, one verdict, now.
         *
         *     **`scan_id` is the client's, not ours.** Section 5: a UUIDv7 generated on
         *     the phone is what makes a retry idempotent, and it is accepted here for the
         *     same reason `/sync` accepts one — an officer on a bad connection retries the
         *     upload, and the second attempt must return the first attempt's answer rather
         *     than create a second inspection record of the same packet.
         *
         *     **`pack_height_mm` is required and has no default.** It could have been
         *     optional, and then a hurried officer would leave it blank, the scan would
         *     fall through to no scale, and the report would come back having quietly
         *     examined 28 of 31 rules with nothing on its face to say so. NO_DATA is the
         *     honest answer to "we had no ruler"; it is the wrong answer to "nobody was
         *     asked". One number at capture time is cheaper than an inspection that has to
         *     be done again.
         *
         *     **The scan runs in a thread.** `run_scan` is several hundred milliseconds of
         *     OpenCV and ONNX Runtime, all of it holding the GIL in C code that never
         *     awaits. Called directly from this coroutine it would block the event loop
         *     for the whole duration, so every other officer's request — including the
         *     cheap ones — would queue behind it. `run_in_threadpool` is the difference
         *     between a concurrency of one and a concurrency of the pool.
         */
        post: operations["scan_photo_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Upload
         * @description The second input channel: a folder of photographs, ingested in the background.
         *
         *     **202, not 200.** Nobody is waiting on this and section 8c puts it on the
         *     low-priority queue for exactly that reason. The response is a receipt with
         *     somewhere to poll.
         *
         *     **Every file is spooled before the job is created, and the job is created
         *     before anything is enqueued.** That order is not incidental. A worker that
         *     picks up a message before its job row exists records a result against
         *     nothing, and the count silently never reaches its total — a job that hangs
         *     with no error, which is the worst thing to hand a district office at 9 pm.
         *
         *     **Rejected files are named, not counted.** "3 of 300 rejected" sends
         *     somebody scrolling through a folder; the filename and the reason do not.
         */
        post: operations["bulk_upload_api_v1_scans_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/bulk/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bulk Status
         * @description How far through a bulk upload the workers are.
         *
         *     Visible to the officer who started it and to a supervisor. Not audited:
         *     section 18 logs who looked at *evidence*, and a progress counter is not
         *     evidence — writing an audit row per poll would bury the reads that matter
         *     under thousands that do not.
         */
        get: operations["bulk_status_api_v1_scans_bulk__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description One scan record, with its verdicts.
         *
         *     **Every read is logged.** Section 18: "Role-based access says who *can* see
         *     something. An audit log records who *did* ... in an enforcement context, who
         *     looked at a pending case is exactly the question that eventually gets
         *     asked."
         */
        get: operations["get_scan_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description The per-product report, in the format asked for. Sections 13 and 8c.
         *
         *     **HTML and DOCX render here; PDF does not.** That split is section 8c's
         *     300-800 ms rule applied honestly rather than uniformly. `python-docx` writes
         *     a zip in a few tens of milliseconds and Jinja is faster still, so making an
         *     officer poll for those would be ceremony. WeasyPrint lays out a full page
         *     and is the renderer the plan actually puts a budget on, so a PDF is rendered
         *     by a worker and served from the derived bucket — `202` with a `Retry-After`
         *     until it exists.
         *
         *     **A report download is audited as `download_evidence`, not `view`.** Section
         *     18's question is not "who opened the app" but who took a copy of enforcement
         *     material out of it, and those two must not be the same row.
         */
        get: operations["get_report_api_v1_scans__scan_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Correction
         * @description Record an officer override.
         *
         *     **Append-only, and the scan is not touched.** Section 5: "Scans are
         *     immutable facts. Corrections are append-only rows, never edits. Nothing is
         *     ever updated in place, so nothing can conflict." That is also the answer to
         *     "what is your merge strategy" — there is nothing to merge.
         *
         *     Section 14: each of these is a labelled training example produced by
         *     somebody already doing the job.
         */
        post: operations["add_correction_api_v1_scans__scan_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Review
         * @description Settle one REVIEW verdict. Section 8b, section 11's Q6.
         *
         *     **Supervisor and above.** The other officer-facing write on this router,
         *     `corrections`, is open to any signed-in officer because relabelling a box is
         *     a statement about what the photograph shows. This is not that: it is a
         *     compliance conclusion recorded against an enforcement record where the
         *     rulepack deliberately declined to reach one, and section 11 already puts the
         *     review queue on the supervisor's dashboard rather than the officer's scan
         *     screen. The guard is here rather than in the navigation because hiding a
         *     link is courtesy and `require_role` is the control.
         *
         *     **The scan is not touched.** Section 5 makes it an immutable fact whose hash
         *     is in the evidence chain; a row that rewrote the verdict would break
         *     `verify_chain` at that record, and correctly so. What changes is that the
         *     scan stops appearing in the queue once every rule that asked for a human has
         *     an answer — which is what `outstanding` reports.
         *
         *     A rule that never asked for review is refused with 409 rather than accepted
         *     quietly. Accepting it would put a decision in the retraining feed that no
         *     verdict ever prompted, and section 14's whole argument for that feed is that
         *     every row in it came from somebody doing the actual job.
         */
        post: operations["resolve_review_api_v1_scans__scan_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup
         * @description Have we seen this pack before? Cache check *before* any model runs.
         *
         *     Returns an identity and nothing else. A cached *verdict* is fetched
         *     separately, because reusing a verdict is a decision about evidence and this
         *     route is about recognition.
         */
        get: operations["lookup_api_v1_skus_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skus/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache
         * @description Warm an officer's offline cache. Section 5.
         *
         *     *"On wifi, pull the 5,000 most-scanned SKUs for the officer's district.
         *     Retail is heavily long-tailed, so a few megabytes covers close to 90% of
         *     what's actually on those shelves."*
         *
         *     Ordered by scan count, because the long tail is the whole reason a few
         *     megabytes is enough — the head of the distribution is most of the shelf.
         */
        get: operations["cache_api_v1_skus_cache_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Rulepack
         * @description The rulepack, readable. Section 12, and `/rules` in the web app.
         *
         *     Deliberately unauthenticated. Section 5 calls the whole legal logic "40 KB
         *     of text, small enough to email", and the argument for rules-as-data is
         *     weakened by hiding them. There is nothing here that is not already in a
         *     gazette.
         */
        get: operations["active_rulepack_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chain/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chain Status
         * @description Verify the evidence chain on demand. Section 6, section 17 M7.
         *
         *     Exposed because a chain nobody ever verifies is a column rather than a
         *     control. Supervisor and above: the result names which record failed, which
         *     is information about a live case.
         */
        get: operations["chain_status_api_v1_chain_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Overview
         * @description Five tiles, a trend, the top eight rules, and the review queue.
         *
         *     The previous period is fetched only when the filters bound one. An unbounded
         *     "all time" view has no previous period, and the tiles say so with a null
         *     change rather than comparing against a window nobody asked for.
         */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Brands */
        get: operations["dashboard_brands_api_v1_dashboard_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/brands/{brand}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Brand Detail
         * @description Q7 — the before-and-after view.
         *
         *     Section 11 calls this *"the most persuasive artefact this system can
         *     produce, because it shows enforcement working"*. A 404 here means we have no
         *     scans of that brand in the filtered window, which is a different statement
         *     from "that brand does not exist" — the message says so.
         */
        get: operations["dashboard_brand_detail_api_v1_dashboard_brands__brand__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Rules */
        get: operations["dashboard_rules_api_v1_dashboard_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Categories */
        get: operations["dashboard_categories_api_v1_dashboard_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Districts */
        get: operations["dashboard_districts_api_v1_dashboard_districts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Health
         * @description Not `/healthz`. That one answers "is the process up"; this one answers
         *     "is the tool still reading labels as well as it did last month".
         */
        get: operations["dashboard_health_api_v1_dashboard_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard Review
         * @description Oldest first. Section 8c: the review queue is a worklist, not a chart.
         *
         *     Rules a supervisor has already settled through `POST /scans/{id}/review`
         *     are dropped, and a scan whose every REVIEW rule is settled leaves the list
         *     entirely. That is the whole point of the resolution endpoint: without this
         *     argument the queue is rebuilt from verdicts on every load and the work
         *     reappears the moment the page is refreshed.
         */
        get: operations["dashboard_review_api_v1_dashboard_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Section 12: brand, barcode, date, district, rule, status.
         *
         *     Newest first — the opposite of the review queue, and for the opposite
         *     reason. Search is "what did I just scan"; the queue is "what has waited
         *     longest".
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Violation Summary
         * @description The dashboard's printable form, as JSON.
         *
         *     Section 13a: *"The dashboard is the live view; the summary is its printable
         *     form."* The PDF and DOCX renderings take this exact structure, so a number
         *     in the report and the same number on screen come from one computation.
         */
        get: operations["violation_summary_api_v1_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Violation Summary Report
         * @description The same summary, laid out to be filed. Sections 13a, 13 and 8c.
         *
         *     **Built over `analytics.summary()`, the identical call the JSON route
         *     makes.** Section 13a asks for the dashboard's printable form, and the cheap
         *     way to build one is a second query shaped for printing — which is how a
         *     department ends up with a tabled document and a screen that disagree about
         *     the same week. There is one computation and three layouts of it.
         *
         *     **All three formats render inline here, and the per-product report's PDF
         *     does not — deliberately.** That route defers because an officer requests a
         *     PDF from a shelf, on a phone, one product at a time, and the artefact has a
         *     scan to be stored against. A summary has neither property: it is an
         *     aggregate over whatever the filters selected at the instant it was asked
         *     for, so there is no scan it belongs to and no capture date to partition it
         *     under, and storing one would mean answering tomorrow's request with
         *     yesterday's numbers. It is also a deliberate export by a supervisor at a
         *     desk, not a step in a shelf-side workflow. So the ~500 ms is spent in the
         *     request, and where WeasyPrint cannot run the route says which two formats
         *     need no native libraries rather than failing.
         */
        get: operations["violation_summary_report_api_v1_summary_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/citation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Citation By Ref
         * @description Resolve any citation string — the "why" button, in one call.
         *
         *     Takes the `rule_ref` verbatim from a verdict, so a client never has to
         *     reformat a citation and no second vocabulary exists to drift.
         */
        get: operations["citation_by_ref_api_v1_rules_citation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search The Gazette
         * @description Tier 2 — free-text search across the gazette corpus. Section 15.
         *
         *     **Declared before `/{rule_id}`**, because a path parameter would otherwise
         *     swallow `/search` and answer it as a lookup for a rule called "search".
         *
         *     **Not cached.** The citation routes carry a day-long `Cache-Control`
         *     because a clause is the same clause tomorrow. A search result is a ranking,
         *     and re-indexing the corpus changes it; serving yesterday's ranking from a
         *     proxy would make an improved index invisible.
         */
        get: operations["search_the_gazette_api_v1_rules_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rule Detail
         * @description One rule of the pack, with the clause it rests on.
         */
        get: operations["rule_detail_api_v1_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_bulk_upload_api_v1_scans_bulk_post */
        Body_bulk_upload_api_v1_scans_bulk_post: {
            /**
             * Images
             * @description Photographs to ingest.
             */
            images: string[];
            /** District */
            district?: string | null;
            /** Category */
            category?: string | null;
        };
        /** Body_scan_photo_api_v1_scans_post */
        Body_scan_photo_api_v1_scans_post: {
            /**
             * Image
             * @description The photograph, JPEG or PNG. Repeat the field to send several photographs OF THE SAME PACKAGE — front, back, side. They are read separately, their evidence is unioned, and the rules are evaluated once on the union. Several packages is /scans/bulk.
             */
            image: string[];
            /**
             * Pack Height Mm
             * @description REQUIRED. Height in millimetres of the pack face that is towards the camera, measured with a ruler. This is what makes the printed-character heights measurable: without it the three height rules under Rule 7(2) and 7(3) cannot be checked. Measure the face in the photograph, not the tallest side of the carton.
             */
            pack_height_mm: number;
            /** Scan Id */
            scan_id?: string | null;
            /** Category */
            category?: string | null;
            /** District */
            district?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Captured At */
            captured_at?: string | null;
            /**
             * Report
             * @default false
             */
            report: boolean;
        };
        /**
         * Box
         * @description An axis-aligned box in *rectified label space*, in pixels.
         *
         *     Rectified means the perspective transform of M1 has already been applied,
         *     so `h` is proportional to true printed height and can be converted to
         *     millimetres by a single scalar. Boxes in raw camera space are useless for
         *     measurement and must not be put here.
         */
        Box: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /** Panel Id */
            panel_id?: ("pdp" | "side" | "back" | "top" | "bottom" | "unknown") | null;
        };
        /**
         * BulkAccepted
         * @description 202 for a bulk upload. Section 8c: nobody is waiting on this.
         */
        BulkAccepted: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected?: string[];
            /** Poll */
            poll: string;
        };
        /** BulkJobStatus */
        BulkJobStatus: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "complete" | "failed";
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Scan Ids */
            scan_ids?: string[];
            /** Errors */
            errors?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * CaptureQuality
         * @description Is this image usable at all?
         *
         *     Every score is normalised to 0..1 with **higher meaning better**, including
         *     `glare_ratio`'s inverse `glare_score`. Mixing directions across a scoreboard
         *     is how a threshold ends up applied the wrong way round, and the wrong way
         *     round here means accepting the blurry frames and rejecting the sharp ones.
         */
        CaptureQuality: {
            /** Usable */
            usable: boolean;
            /** Blur Score */
            blur_score: number;
            /** Glare Ratio */
            glare_ratio: number;
            /** Exposure Score */
            exposure_score: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Faults
             * @default []
             */
            faults: ("blur" | "glare" | "underexposed" | "overexposed" | "resolution")[];
            /**
             * Blocking Faults
             * @default []
             */
            blocking_faults: ("blur" | "glare" | "underexposed" | "overexposed" | "resolution")[];
            /**
             * Subject Ratio
             * @default 1
             */
            subject_ratio: number;
            /** Reason */
            reason?: string | null;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
        };
        /**
         * ChainStatusResponse
         * @description Section 6 and section 18 — exposed so tamper-evidence is checkable.
         *
         *     A chain nobody ever verifies is a column, not a control.
         */
        ChainStatusResponse: {
            /** Checked */
            checked: number;
            /** Ok */
            ok: boolean;
            /** Head Sha256 */
            head_sha256: string | null;
            /** Failures */
            failures?: string[];
            /**
             * Anchor Status
             * @default unanchored
             * @enum {string}
             */
            anchor_status: "ok" | "unanchored" | "failed" | "unreadable";
            /**
             * Anchors
             * @default 0
             */
            anchors: number;
            /**
             * Anchors Checked
             * @default 0
             */
            anchors_checked: number;
            /** Anchor Failures */
            anchor_failures?: string[];
        };
        /**
         * CorrectionRequest
         * @description An officer override. Append-only; never an edit.
         *
         *     Section 5: "Corrections are append-only rows, never edits. Nothing is ever
         *     updated in place, so nothing can conflict." Section 14: every one of these
         *     is also a labelled training example, produced by someone already doing the
         *     job.
         */
        CorrectionRequest: {
            /** Box Index */
            box_index?: number | null;
            /** From Field */
            from_field?: string | null;
            /** To Field */
            to_field: string;
        };
        /** CurrentUser */
        CurrentUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "officer" | "supervisor" | "admin";
            /** District */
            district?: string | null;
        };
        /**
         * Declaration
         * @description One extracted declaration: what it says, where it sits, how tall it is.
         */
        Declaration: {
            /**
             * Field
             * @enum {string}
             */
            field: "mrp" | "net_quantity" | "mfg_date" | "expiry_date" | "manufacturer" | "packer" | "importer" | "consumer_care" | "country_of_origin" | "generic_name" | "batch" | "marketing_text" | "nutrition" | "ingredients" | "storage_use" | "fssai_licence" | "licence" | "barcode" | "unit_sale_price" | "other";
            /** Text */
            text: string;
            /**
             * Script
             * @enum {string}
             */
            script: "latin" | "devanagari" | "other";
            box: components["schemas"]["Box"];
            /** Height Px */
            height_px: number;
            /** Height Mm */
            height_mm?: number | null;
            /** Height Mm Tolerance */
            height_mm_tolerance?: number | null;
            /** Scale Tier */
            scale_tier?: ("A" | "B" | "C") | null;
            /** Ocr Confidence */
            ocr_confidence: number;
            /** Field Confidence */
            field_confidence: number;
            /** Contrast Ratio */
            contrast_ratio?: number | null;
            /** Contrast Ratio Tolerance */
            contrast_ratio_tolerance?: number | null;
            /** Char Boxes */
            char_boxes?: components["schemas"]["Box"][];
            numeral_box?: components["schemas"]["Box"] | null;
            /** Numeral Height Px */
            numeral_height_px?: number | null;
            /**
             * Frame Id
             * @default 0
             */
            frame_id: number;
            /**
             * Is Embossed
             * @default false
             */
            is_embossed: boolean;
            /**
             * Text Rotation K
             * @default 0
             */
            text_rotation_k: number;
        };
        /**
         * DeclarationSet
         * @description The complete output of extraction, and the ONLY input to the rules engine.
         *
         *     The engine receives this and nothing else — no image, no file handle, no
         *     database session. That wall is what lets the identical engine judge an
         *     e-commerce listing that never had pixels.
         */
        DeclarationSet: {
            /**
             * Source
             * @enum {string}
             */
            source: "photo" | "bulk_image" | "listing_text";
            /** Declarations */
            declarations?: components["schemas"]["Declaration"][];
            geometry?: components["schemas"]["LabelGeometry"];
            /**
             * Coverage
             * @default 0
             */
            coverage: number;
            /**
             * Degradation Tier
             * @default L0
             * @enum {string}
             */
            degradation_tier: "L0" | "L1" | "L2" | "L3" | "L4";
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Model Versions */
            model_versions?: {
                [key: string]: string;
            };
            /** Raw Text */
            raw_text?: string | null;
            /**
             * Frame Count
             * @default 1
             */
            frame_count: number;
        };
        /**
         * EvidenceInfo
         * @description What happened to the photograph. Sections 6 and 18.
         *
         *     On screen this is one line — "photograph stored" or "no photograph: repeat
         *     SKU". It is in the response rather than left to a log because three quite
         *     different things all end with no object in the bucket, and an officer who
         *     later has to explain a finding needs to know which one applied at the time
         *     rather than reconstructing it from a retention policy.
         */
        EvidenceInfo: {
            /** Stored */
            stored: boolean;
            /** Reason */
            reason: string;
            /** Key */
            key?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Tier */
            tier?: string | null;
            /**
             * Deferred
             * @default false
             */
            deferred: boolean;
            /**
             * Faces Blurred
             * @default 0
             */
            faces_blurred: number;
            /**
             * Faces On Package
             * @default 0
             */
            faces_on_package: number;
        };
        /**
         * FrameInfo
         * @description One photograph of the pack, and what it contributed.
         *
         *     Deliberately thin. Everything an officer needs while standing in the shop —
         *     was this shot usable, did it show a declaration panel, is it stored — and
         *     nothing about geometry or scale, which belong to the union rather than to
         *     any one frame.
         */
        FrameInfo: {
            /** Frame */
            frame: number;
            /** Exit Path */
            exit_path: string;
            /** Read */
            read: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            capture_quality?: components["schemas"]["CaptureQuality"] | null;
            framing?: components["schemas"]["Framing"] | null;
            /** Image Key */
            image_key?: string | null;
            /** Image Sha256 */
            image_sha256?: string | null;
            /**
             * Stored
             * @default false
             */
            stored: boolean;
        };
        /**
         * Framing
         * @description Did this frame contain anything the rules could be applied to?
         *
         *     **A measurement, never a verdict, and never a suppressor.** It changes no
         *     status, hides no evidence and is not read anywhere in `rules/`. Withdrawing
         *     the inference from silence is already handled — and handled better, against
         *     the live rulepack — by `rules.checks._common.reading_supports_an_absence`.
         *     This exists for the one thing that guard cannot do: tell the officer holding
         *     the phone *why* the screen came back thin, and what to point the camera at.
         *
         *     Nothing here fires when a declaration *was* found. A frame naming two of
         *     the six may be a clipped panel or may be a genuinely under-declared package,
         *     and no signal available to us separates those. Reporting the first as a
         *     framing fault would give every under-declared pack an excuse, so the fault
         *     is emitted only when the count is zero.
         */
        Framing: {
            /** Shows Declarations */
            shows_declarations: boolean;
            /** Mandatory Found */
            mandatory_found: number;
            /** Mandatory Expected */
            mandatory_expected: number;
            /** Text Regions */
            text_regions: number;
            /** Fault */
            fault?: ("no_declaration_panel" | "wrong_panel") | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * GeoPoint
         * @description Truncated before storage — section 18, and `Settings.geo_precision_dp`.
         *
         *     Accepted at full precision because a browser reports what it reports;
         *     reduced on the way in, so the coarse value is the only one ever written.
         */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Rulepack Version */
            rulepack_version: string;
            /** Rules Loaded */
            rules_loaded: number;
            /** Models Present */
            models_present: number;
            /** Models Expected */
            models_expected: number;
            /**
             * Storage
             * @default memory
             * @enum {string}
             */
            storage: "memory" | "sql";
            /** Detail */
            detail?: string[];
        };
        /**
         * LabelGeometry
         * @description Everything the geometric rules need to know about the label as a whole.
         */
        LabelGeometry: {
            /** Label Area Cm2 */
            label_area_cm2?: number | null;
            /** Pdp Polygon */
            pdp_polygon?: [
                number,
                number
            ][] | null;
            /** Mm Per Px */
            mm_per_px?: number | null;
            /** Mm Per Px Tolerance */
            mm_per_px_tolerance?: number | null;
            /**
             * Rectified
             * @default false
             */
            rectified: boolean;
            /** Scale Tier */
            scale_tier?: ("A" | "B" | "C") | null;
            /**
             * Frame Id
             * @default 0
             */
            frame_id: number;
        };
        /**
         * ListingScanRequest
         * @description The third input channel. No pixels at all.
         *
         *     Section 3: "the PS names three inputs and one is pure text from an
         *     e-commerce listing. If OCR is wired straight into the rules, that third
         *     channel becomes a rewrite instead of an afternoon's work."
         */
        ListingScanRequest: {
            /** Text */
            text: string;
            /** Category */
            category?: string | null;
            /** District */
            district?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ReviewResolutionRequest
         * @description A human's decision on a verdict the rulepack declined to decide.
         *
         *     Section 8b: *"every REVIEW verdict lands there, one-click resolve,
         *     resolution stored as a labelled example for retraining."*
         *
         *     `rule_id` is required and there is no "resolve the whole scan" shortcut. A
         *     scan reaches the queue because one or more specific rules came back REVIEW,
         *     and each is a separate question — a marginal MRP height and an unreadable
         *     net quantity are not settled by one click, and pretending otherwise would
         *     file a decision nobody made against the second one.
         */
        ReviewResolutionRequest: {
            /** Rule Id */
            rule_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "complies" | "does_not_comply" | "recapture";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ReviewResolutionResponse */
        ReviewResolutionResponse: {
            /**
             * Scan Id
             * Format: uuid
             */
            scan_id: string;
            /** Rule Id */
            rule_id: string;
            /** Decision */
            decision: string;
            /**
             * Officer Id
             * Format: uuid
             */
            officer_id: string;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at: string;
            /** Outstanding */
            outstanding: string[];
        };
        /**
         * ScanResponse
         * @description What an officer sees, and in the order the scan screen renders it.
         *
         *     `latency_ms`, `degradation_tier` and `coverage` are not diagnostics here —
         *     section 11 requires all three on screen for every scan. "An officer must
         *     know how much the system understood before trusting a verdict."
         */
        ScanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Exit Path
             * @enum {string}
             */
            exit_path: "unusable" | "cache_hit" | "no_package" | "full" | "listing_text";
            /**
             * Source
             * @enum {string}
             */
            source: "photo" | "bulk_image" | "listing_text";
            /**
             * Degradation Tier
             * @enum {string}
             */
            degradation_tier: "L0" | "L1" | "L2" | "L3" | "L4";
            /** Coverage */
            coverage: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cache Hit */
            cache_hit: boolean;
            declarations?: components["schemas"]["DeclarationSet"] | null;
            /** Verdicts */
            verdicts?: components["schemas"]["Verdict"][];
            /**
             * Message
             * @default
             */
            message: string;
            /** Model Versions */
            model_versions?: {
                [key: string]: string;
            };
            /**
             * Rulepack Version
             * @default
             */
            rulepack_version: string;
            /** Record Sha256 */
            record_sha256?: string | null;
            /** Chain Seq */
            chain_seq?: number | null;
            /**
             * Report Status
             * @default queued
             * @enum {string}
             */
            report_status: "queued" | "ready" | "not_requested";
            evidence?: components["schemas"]["EvidenceInfo"] | null;
            capture_quality?: components["schemas"]["CaptureQuality"] | null;
            framing?: components["schemas"]["Framing"] | null;
            /** Frames */
            frames?: components["schemas"]["FrameInfo"][];
        };
        /** SkuCacheResponse */
        SkuCacheResponse: {
            /** District */
            district: string | null;
            /** Count */
            count: number;
            /** Skus */
            skus: components["schemas"]["SkuSummary"][];
        };
        /** SkuLookupResponse */
        SkuLookupResponse: {
            /** Hit */
            hit: boolean;
            /**
             * Matched On
             * @default none
             * @enum {string}
             */
            matched_on: "barcode" | "phash" | "none";
            sku?: components["schemas"]["SkuSummary"] | null;
        };
        /** SkuSummary */
        SkuSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Brand */
            brand: string;
            /** Brand Group */
            brand_group?: string | null;
            /** Variant */
            variant?: string | null;
            /** Pack Size */
            pack_size: string;
            /** Category */
            category: string;
            /** Barcode */
            barcode?: string | null;
            /** Phash */
            phash?: string | null;
            /**
             * Scan Count
             * @default 0
             */
            scan_count: number;
            /** Label W Mm */
            label_w_mm?: number | null;
            /** Label H Mm */
            label_h_mm?: number | null;
            /**
             * Label Mm Observations
             * @default 0
             */
            label_mm_observations: number;
            /** Label W Mm Stddev */
            label_w_mm_stddev?: number | null;
        };
        /**
         * SyncItem
         * @description One queued scan from an offline outbox.
         */
        SyncItem: {
            /**
             * Id
             * Format: uuid
             * @description Client-generated UUIDv7 — time-ordered, replay-safe.
             */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "photo" | "bulk_image" | "listing_text";
            /**
             * Degradation Tier
             * @enum {string}
             */
            degradation_tier: "L0" | "L1" | "L2" | "L3" | "L4";
            /** Declaration Set */
            declaration_set: {
                [key: string]: unknown;
            };
            /** Coverage */
            coverage?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /** Image Key */
            image_key?: string | null;
            /** Image Sha256 */
            image_sha256?: string | null;
            geo?: components["schemas"]["GeoPoint"] | null;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Model Versions */
            model_versions?: {
                [key: string]: string;
            };
            /** Rulepack Version */
            rulepack_version: string;
            /** District */
            district?: string | null;
        };
        /** SyncRequest */
        SyncRequest: {
            /** Scans */
            scans: components["schemas"]["SyncItem"][];
        };
        /** SyncResponse */
        SyncResponse: {
            /** Accepted */
            accepted: number;
            /** Created */
            created: number;
            /** Duplicates */
            duplicates: number;
            /** Results */
            results: components["schemas"]["SyncResult"][];
        };
        /** SyncResult */
        SyncResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created */
            created: boolean;
            /** Chain Seq */
            chain_seq: number;
            /** Record Sha256 */
            record_sha256: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description Access token lifetime, seconds.
             */
            expires_in: number;
            /**
             * Role
             * @enum {string}
             */
            role: "officer" | "supervisor" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @description One rule, one decision, one gazette citation.
         *
         *     Every verdict carries ``rule_ref`` — that citation is also the retrieval
         *     key for the rule explainer (section 15 tier 1). We never search for
         *     Rule 7(2); we know it is Rule 7(2).
         */
        Verdict: {
            /** Rule Id */
            rule_id: string;
            /** Rule Ref */
            rule_ref: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FAIL" | "NOT_APPLICABLE" | "REVIEW" | "NO_DATA";
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /** Field */
            field?: ("mrp" | "net_quantity" | "mfg_date" | "expiry_date" | "manufacturer" | "packer" | "importer" | "consumer_care" | "country_of_origin" | "generic_name" | "batch" | "marketing_text" | "nutrition" | "ingredients" | "storage_use" | "fssai_licence" | "licence" | "barcode" | "unit_sale_price" | "other") | null;
            /** Found */
            found?: string | null;
            /** Expected */
            expected: string;
            /** Message */
            message: string;
            /** Measured */
            measured?: number | null;
            /** Threshold */
            threshold?: number | null;
            /** Tolerance */
            tolerance?: number | null;
            /**
             * Unit
             * @default mm
             * @enum {string}
             */
            unit: "mm" | "ratio" | "count" | "cm2";
            /**
             * Respondent
             * @default manufacturer
             * @enum {string}
             */
            respondent: "manufacturer" | "packer" | "importer" | "dealer";
            /**
             * Advisory
             * @default false
             */
            advisory: boolean;
            /** Suppressed By */
            suppressed_by?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    scan_listing_api_v1_scans_listing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_v1_scans_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_photo_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_photo_api_v1_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_upload_api_v1_scans_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_bulk_upload_api_v1_scans_bulk_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_status_api_v1_scans_bulk__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_scans__scan_id__report_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_correction_api_v1_scans__scan_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_review_api_v1_scans__scan_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResolutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_api_v1_skus_lookup_get: {
        parameters: {
            query?: {
                barcode?: string | null;
                /** @description 64-bit perceptual hash, hex. */
                phash?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_api_v1_skus_cache_get: {
        parameters: {
            query?: {
                district?: string | null;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuCacheResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    active_rulepack_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chain_status_api_v1_chain_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainStatusResponse"];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_brands_api_v1_dashboard_brands_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                limit?: number;
                offset?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_brand_detail_api_v1_dashboard_brands__brand__get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path: {
                brand: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_rules_api_v1_dashboard_rules_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                limit?: number;
                offset?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_categories_api_v1_dashboard_categories_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                limit?: number;
                offset?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_districts_api_v1_dashboard_districts_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                limit?: number;
                offset?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_health_api_v1_dashboard_health_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_review_api_v1_dashboard_review_get: {
        parameters: {
            query?: {
                limit?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
                limit?: number;
                offset?: number;
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    violation_summary_api_v1_summary_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    violation_summary_report_api_v1_summary_report_get: {
        parameters: {
            query?: {
                format?: "html" | "docx" | "pdf";
                from?: string | null;
                to?: string | null;
                district?: string | null;
                category?: string | null;
                severity?: ("low" | "medium" | "high") | null;
                brand?: string | null;
                rule_id?: string | null;
                status?: ("PASS" | "FAIL" | "REVIEW") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    citation_by_ref_api_v1_rules_citation_get: {
        parameters: {
            query: {
                ref: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_the_gazette_api_v1_rules_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rule_detail_api_v1_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
