"""The editable format. AKSHAR.md sections 13 and 15b.

    "python-docx 1.1 — the editable format is explicitly required by the problem
     statement."                                                  -- section 15b

**Why this is not "the PDF, converted".** An officer does not want a facsimile;
they want to add a paragraph, correct a spelling, and sign it. That means real
Word paragraphs and real tables, which is why this walks the report model
directly instead of parsing the HTML — an HTML-to-DOCX conversion produces a
document whose every line is a nested table and which nobody can edit.

**It reads the same `ProductReport` the template reads.** Section 13's
requirement that the five unit-symbol checks sit in a separate advisory block is
a *field* on that model, not a filter in the Jinja template, precisely so this
file cannot forget it. Every heading below corresponds to one attribute; if a
new category of finding is added to the model and not here, its section is
absent and visibly so, rather than being silently folded into the violations.

**No native dependencies.** `python-docx` is pure Python over a zip file, so
this works where WeasyPrint cannot — which on a Windows or macOS developer
machine is always. A deployment that can produce no PDF can still produce the
format the problem statement actually names.
"""

from __future__ import annotations

import io
from typing import Any

_HEADING_RULE = "Heading 2"


def _add_table(document: Any, headers: list[str], widths: list[float] | None = None) -> Any:
    table = document.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for cell, text in zip(table.rows[0].cells, headers, strict=True):
        run = cell.paragraphs[0].add_run(text)
        run.bold = True
    if widths:
        from docx.shared import Cm

        for row in table.rows:
            for cell, width in zip(row.cells, widths, strict=True):
                cell.width = Cm(width)
    return table


def _findings_table(document: Any, findings: tuple[Any, ...], *, observed: bool = True) -> None:
    headers = ["Provision", "Finding", "Observed", "Status"] if observed else [
        "Provision",
        "Observation",
        "Observed",
    ]
    table = _add_table(document, headers, [4.0, 7.0, 3.5, 2.0][: len(headers)])
    for finding in findings:
        cells = table.add_row().cells
        cells[0].text = f"{finding.rule_ref}\n{finding.rule_id}"
        cells[1].text = f"{finding.message}\nRemedy: {finding.remediation}"
        cells[2].text = finding.measurement or finding.found or "—"
        if observed:
            cells[3].text = f"{finding.status} ({finding.severity})"


def to_docx(report: Any) -> bytes:
    """Build the .docx and return its bytes.

    Bytes rather than a path, for the same reason `evidence/storage.py` takes a
    payload: the caller decides whether this goes to MinIO, into an HTTP
    response or onto a disk, and this module opens nothing.
    """
    from docx import Document
    from docx.shared import Pt

    document = Document()
    style = document.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    document.add_heading("Package declaration check", level=1)
    intro = document.add_paragraph()
    intro.add_run(
        "Legal Metrology (Packaged Commodities) Rules, 2011 — form of report "
        "modelled on Rule 19(2), Seventh Schedule, Form A.\n"
    )
    intro.add_run(f"Generated by AKSHAR from rulepack {report.provenance.rulepack_version}.")

    document.add_paragraph(report.headline).runs[0].bold = True

    # -- Part A --------------------------------------------------------------
    document.add_heading("Part A — Particulars of the package", level=2)
    particulars = _add_table(document, ["Item", "Particulars"], [6.0, 10.5])
    for label, value in [
        ("Commodity", report.package.title),
        ("Category", report.package.category or "—"),
        ("Manufacturer / packer / importer", report.package.manufacturer or "not read"),
        ("Net quantity as declared", report.package.net_quantity or "not read"),
        ("Retail sale price as declared", report.package.mrp or "not read"),
        ("Barcode", report.package.barcode or "—"),
        ("Date and time of check", report.captured_at.strftime("%d %B %Y, %H:%M %Z")),
        ("District", report.district or "—"),
        ("Scan reference", report.scan_id),
    ]:
        cells = particulars.add_row().cells
        cells[0].text = label
        cells[1].text = str(value)

    # -- Parts B/C/D, named rather than omitted ------------------------------
    document.add_heading("Parts B, C and D — Net quantity by weight", level=2)
    document.add_paragraph(report.form_a_not_applicable_reason)
    parts = _add_table(document, ["Part", "Title", "Status"], [2.5, 9.0, 5.0])
    for part, title in report.form_a_not_applicable:
        cells = parts.add_row().cells
        cells[0].text = part
        cells[1].text = title
        cells[2].text = "Not applicable"

    # -- Part E --------------------------------------------------------------
    document.add_heading("Part E — Findings on the declarations", level=2)
    if report.violations:
        _findings_table(document, report.violations)
    else:
        document.add_paragraph(
            "No contravention was found in the declarations that could be checked."
        )
    if report.reviews:
        document.add_paragraph(
            "A finding marked REVIEW is a measurement that falls within this system's "
            "own measurement error of the prescribed limit. It is not asserted as a "
            "contravention and requires physical examination before any action is taken."
        )

    # -- what was not checked ------------------------------------------------
    if report.not_checked:
        document.add_heading("Checks that could not be carried out", level=2)
        document.add_paragraph(
            "These provisions were not evaluated. Their absence from Part E is not a "
            "finding of compliance."
        )
        table = _add_table(document, ["Provision", "Reason"], [5.0, 11.5])
        for finding in report.not_checked:
            cells = table.add_row().cells
            cells[0].text = f"{finding.rule_ref}\n{finding.rule_id}"
            cells[1].text = finding.message

    # -- section 13c advisory block, kept apart ------------------------------
    if report.advisory:
        document.add_heading("Advisory — printing of unit symbols", level=2)
        document.add_paragraph(
            "These are formatting defects under the National Standards (Prescription "
            "and Verification) Rules, 2011, Third Schedule. They are reported "
            "separately from Part E and no contravention of the Packaged Commodities "
            "Rules is asserted on their basis."
        )
        _findings_table(document, report.advisory, observed=False)

    # -- the exhibit ---------------------------------------------------------
    #
    # Embedded, not linked. A DOCX is the format an officer edits and forwards,
    # and a linked image is the half of a document that does not survive being
    # attached to an email.
    document.add_heading("Exhibit — the label as it was read", level=2)
    if report.exhibit is not None:
        from docx.shared import Inches

        document.add_picture(io.BytesIO(report.exhibit.jpeg), width=Inches(6.2))
        document.add_paragraph(
            "The photograph flattened to the plane of the label, which is the image "
            "every measurement in Part E was taken from. Each box is one declaration "
            "the system read; the height printed beside it is the figure this report "
            "relies on."
        )
        for label, meaning, _colour in report.exhibit.legend:
            # The swatch is a coloured square in HTML and a named colour here.
            # Word can carry the colour, but a legend whose only distinguishing
            # mark is a hue is unreadable on the monochrome printer a district
            # office actually has, so the label carries the meaning in both.
            document.add_paragraph(f"{label} — {meaning}", style="List Bullet")
        document.add_paragraph(f"SHA-256 {report.exhibit.sha256}")
    else:
        document.add_paragraph(report.exhibit_note)

    # -- reproducibility -----------------------------------------------------
    document.add_heading("How this check was carried out", level=2)
    provenance = _add_table(document, ["Item", "Value"], [6.0, 10.5])
    rows: list[tuple[str, str]] = [
        ("Rulepack", report.provenance.rulepack_version),
        ("Degradation tier", report.provenance.degradation_tier),
        (
            "Label coverage",
            "—" if report.provenance.coverage is None else f"{report.provenance.coverage:.0%}",
        ),
        *[(name, version) for name, version in report.provenance.model_versions.items()],
        ("Photograph", report.provenance.image_sha256 or "not retained"),
        ("Record digest", report.provenance.record_sha256 or "—"),
        (
            "Chain position",
            "—" if report.provenance.chain_seq is None else str(report.provenance.chain_seq),
        ),
    ]
    for label, value in rows:
        cells = provenance.add_row().cells
        cells[0].text = label
        cells[1].text = str(value)
    document.add_paragraph(report.provenance.evidence_note)

    # -- Part F --------------------------------------------------------------
    document.add_heading("Part F — Signatures", level=2)
    signatures = _add_table(document, ["Authorised officer", "Manufacturer's representative"], [8.0, 8.0])
    cells = signatures.add_row().cells
    cells[0].text = f"\n\n{report.officer_name or ''}\n{report.officer_designation}"
    cells[1].text = "\n\nName, signature and date"

    return _bytes(document)


def summary_to_docx(report: Any) -> bytes:
    """The violation summary as an editable document. Sections 13a and 11.

    Walks `reports.summary_model.SummaryReport` — the same object the HTML
    template walks — so the printed and the editable summary carry the same
    figures in the same order. Every cell arrives already formatted: an em dash
    for a rate that does not exist is decided in the model, once, because a
    renderer that turned None into "0%" here would report the districts nobody
    visited as fully compliant.
    """
    from docx import Document
    from docx.shared import Pt

    document = Document()
    style = document.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    document.add_heading("Violation summary", level=1)
    intro = document.add_paragraph()
    intro.add_run(
        f"Legal Metrology (Packaged Commodities) Rules, 2011 — {report.scope}.\n"
    )
    intro.add_run(
        f"Period: {report.period}. Prepared "
        f"{report.generated_at.strftime('%d %B %Y, %H:%M')}"
        + (f" — {report.office}." if report.office else ".")
    )

    document.add_paragraph(report.headline).runs[0].bold = True
    if report.coverage_note:
        document.add_paragraph(report.coverage_note)

    # -- the tiles, as a table so they survive being pasted into a memo -------
    tiles = _add_table(
        document,
        ["Scans", "Checked", "Products", "Contravention rate", "High severity", "For examination"],
        [2.7] * 6,
    )
    cells = tiles.add_row().cells
    for index, value in enumerate(
        (
            report.scans,
            report.conclusive,
            report.unique_skus,
            report.non_compliance_rate,
            report.high_severity,
            report.awaiting_review,
        )
    ):
        cells[index].text = str(value)

    for table in report.tables:
        document.add_heading(table.title, level=2)
        if not table.rows:
            document.add_paragraph(table.empty_note)
            continue
        widths = [5.5] + [(11.0 / max(1, len(table.headers) - 1))] * (len(table.headers) - 1)
        rendered = _add_table(document, list(table.headers), widths)
        for row in table.rows:
            cells = rendered.add_row().cells
            cells[0].text = row.label + (f"\n{row.note}" if row.note else "")
            for index, cell in enumerate(row.cells, start=1):
                cells[index].text = cell
        if table.footnote:
            document.add_paragraph(table.footnote)

    # -- and how they were counted -------------------------------------------
    document.add_heading("How these figures were counted", level=2)
    for title, explanation in report.counting_rules:
        paragraph = document.add_paragraph()
        paragraph.add_run(f"{title}. ").bold = True
        paragraph.add_run(explanation)

    document.add_paragraph(
        "Every figure above is produced by the same computation that serves the "
        "live dashboard, so this document and the screen cannot report different "
        "numbers for the same period. Mean coverage of the label text read across "
        f"these scans: {report.mean_coverage}."
    )
    document.add_paragraph(
        "This summary reports declarations as printed on packages, checked from "
        "photographs. No package was opened, weighed or measured for net quantity, "
        "so nothing here is a finding about the quantity actually contained in a "
        "package."
    )

    document.add_heading("Signature", level=2)
    signatures = _add_table(
        document, ["Authorised officer", "Controller / Assistant Controller"], [8.0, 8.0]
    )
    cells = signatures.add_row().cells
    cells[0].text = f"\n\n{report.prepared_by or ''}\nLegal Metrology Department"
    cells[1].text = "\n\nName, signature and date"

    return _bytes(document)


def _bytes(document: Any) -> bytes:
    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


__all__ = ["summary_to_docx", "to_docx"]
