"""Synthetic labels with known ground truth.

The 40 ruler-measured photographs are the *accuracy* ground truth and they do
not exist yet — they need a person, a packet and a ruler. But correctness and
accuracy are different questions, and the correctness one can be answered now:
if we draw a glyph exactly 24 pixels tall and photograph it through a known
homography, the pipeline must recover 24 pixels.

That is what this module builds. It cannot tell us the real-world error — only
a ruler can — but it catches every sign error, every coordinate-frame mix-up
and every off-by-a-descender, which is where measurement code actually goes
wrong. When the photographs arrive, the same assertions run against them with
the tolerance tightened.

Nothing here is used outside tests.
"""

from __future__ import annotations

from dataclasses import dataclass

import cv2
import numpy as np

_FONT = cv2.FONT_HERSHEY_SIMPLEX


@dataclass(frozen=True, slots=True)
class DrawnText:
    """Where a string was drawn and how tall it truly is."""

    text: str
    x: float
    y: float
    w: float
    h: float
    cap_height_px: float
    baseline_y: float


def font_scale_for_cap_height(cap_px: float, thickness: int = 2) -> float:
    """Solve `cv2.putText`'s scale for a target cap height.

    `getTextSize` reports the height of the glyph box above the baseline, which
    for an all-caps or all-digit string is exactly the cap height — so a digit
    string drawn this way has a cap height we know to the pixel, which is the
    whole point of the fixture.
    """
    (_, base_h), _ = cv2.getTextSize("0", _FONT, 1.0, thickness)
    return float(cap_px) / float(base_h)


def draw_text(
    image: np.ndarray,
    text: str,
    *,
    baseline: tuple[int, int],
    cap_px: float,
    colour: tuple[int, int, int] = (20, 20, 20),
    thickness: int = 2,
) -> DrawnText:
    """Draw `text` with its cap height set to `cap_px`, and report the truth."""
    scale = font_scale_for_cap_height(cap_px, thickness)
    (w, h), _ = cv2.getTextSize(text, _FONT, scale, thickness)
    cv2.putText(image, text, baseline, _FONT, scale, colour, thickness, cv2.LINE_AA)
    return DrawnText(
        text=text,
        x=float(baseline[0]),
        y=float(baseline[1] - h),
        w=float(w),
        h=float(h),
        cap_height_px=float(h),
        baseline_y=float(baseline[1]),
    )


def blank_label(
    width: int = 760,
    height: int = 520,
    *,
    bg: int = 245,
) -> np.ndarray:
    return np.full((height, width, 3), bg, dtype=np.uint8)


def on_canvas(
    label: np.ndarray,
    *,
    canvas_size: tuple[int, int] = (1200, 900),
    origin: tuple[int, int] = (230, 190),
    background: int = 70,
) -> np.ndarray:
    """Place a label on a darker background, the way a pack sits on a counter.

    The contrast at the label's edge is what `find_label_quad` looks for. A
    white label on a white page has no findable outline, and rectification
    correctly falls through to the detector box — which is a different test.
    """
    canvas = np.full((canvas_size[1], canvas_size[0], 3), background, dtype=np.uint8)
    x, y = origin
    h, w = label.shape[:2]
    canvas[y : y + h, x : x + w] = label
    return canvas


def draw_marker(
    image: np.ndarray,
    centre: tuple[int, int],
    edge_px: float,
    *,
    marker_id: int = 7,
    dictionary: str = "DICT_4X4_50",
    quiet_zone: float = 0.25,
) -> float:
    """Draw a REAL ArUco marker. Returns its edge length in pixels.

    This is genuinely different from the coin fixture it replaces, and the
    difference matters. `draw_coin` painted something *coin-like* and the test
    then asserted that a circle detector found a circle — which is close to
    asserting that `HoughCircles` works. Here the bits are generated by the same
    OpenCV dictionary the detector decodes against, so the marker either decodes
    to `marker_id` or it does not. There is no way for the fixture to be
    charitable to the code under test.

    `quiet_zone` is the white margin ArUco needs around the black border. Omit
    it and detection fails on a fixture that looks perfectly fine to a human,
    which is a real and easily-misdiagnosed failure in the field too — it is why
    the printed card must not have the marker running to its edge.
    """
    attr = getattr(cv2.aruco, dictionary)
    side = max(round(edge_px), 8)
    bits = cv2.aruco.generateImageMarker(cv2.aruco.getPredefinedDictionary(attr), marker_id, side)

    pad = round(side * quiet_zone)
    tile = np.full((side + 2 * pad, side + 2 * pad), 255, np.uint8)
    tile[pad : pad + side, pad : pad + side] = bits
    if image.ndim == 3:
        tile = cv2.cvtColor(tile, cv2.COLOR_GRAY2BGR)

    th, tw = tile.shape[:2]
    x0 = int(centre[0] - tw // 2)
    y0 = int(centre[1] - th // 2)
    h, w = image.shape[:2]
    if x0 < 0 or y0 < 0 or x0 + tw > w or y0 + th > h:
        raise ValueError(
            f"marker of {tw}x{th} px at {centre} falls outside a {w}x{h} canvas; "
            f"a clipped quiet zone would make this fixture undetectable"
        )
    image[y0 : y0 + th, x0 : x0 + tw] = tile
    return float(side)


def photograph(
    canvas: np.ndarray,
    *,
    tilt: float = 0.10,
    yaw: float = 0.06,
) -> tuple[np.ndarray, np.ndarray]:
    """Apply a known perspective distortion — a photo taken off-axis.

    Returns (image, homography_applied). `tilt` shrinks the top edge and `yaw`
    the right edge, each as a fraction of the frame, which is what holding a
    phone above and to the side of a packet actually does.
    """
    h, w = canvas.shape[:2]
    src = np.float32([[0, 0], [w - 1, 0], [w - 1, h - 1], [0, h - 1]])
    dst = np.float32(
        [
            [w * tilt, h * yaw],
            [w - 1 - w * tilt * 0.35, 0],
            [w - 1, h - 1 - h * yaw * 0.5],
            [w * 0.02, h - 1],
        ]
    )
    matrix = cv2.getPerspectiveTransform(src, dst)
    warped = cv2.warpPerspective(
        canvas, matrix, (w, h), flags=cv2.INTER_CUBIC, borderValue=(70, 70, 70)
    )
    return warped, matrix


__all__ = [
    "DrawnText",
    "blank_label",
    "draw_marker",
    "draw_text",
    "font_scale_for_cap_height",
    "on_canvas",
    "photograph",
]
